SkyTracker.Web/Controllers/AircraftController.cs
namespace SkyTracker.Web.Controllers;

using Azure.Storage.Blobs;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using SkyTracker.Services.Data.Interfaces;
using Configuration;

using ViewModels.Aircraft;

using static Common.GeneralApplicationContants;
using static Common.UserRoleNames;
using static Configuration.UploadBlob;

/// <summary>
/// Aircraft Controller. Used for managing aircrafts.
/// </summary>

[Authorize]
public class AircraftController : Controller
{
    private readonly IAircraftService _aircraftService;
    private readonly BlobServiceClient _blobServiceClient;
    private readonly IWebHostEnvironment _hostingEnvironment;

    public AircraftController(IAircraftService aircraftService, BlobServiceClient blobServiceClient, IWebHostEnvironment hostingEnvironment)
    {
        _aircraftService = aircraftService;
        _blobServiceClient = blobServiceClient;
        _hostingEnvironment = hostingEnvironment;
    }

    [TempData]
    public string StatusMessage { get; set; }

    [HttpGet]
    public async Task<IActionResult> All()
    {
        var aircraft = await _aircraftService.GetAllAircraftAsync();

        return View(aircraft);
    }

    [HttpGet]
    public async Task<IActionResult> GetDetailsAircraft(string aircraftId)
    {
        var aircraft = await _aircraftService.GetAircraftDetailsByIdAsync(aircraftId);

        string localPath = Path.Combine(_hostingEnvironment.WebRootPath, AircraftImagesBlobRelativePath, aircraft.Registration.ToLower());

        if (System.IO.File.Exists(Path.ChangeExtension(localPath, ".jpg")))
        {
            aircraft.ImageUrl = Path.Combine(AircraftImagesBlobRelativePath, aircraft.Registration.ToLower() + ".jpg");
        }
        else if (System.IO.File.Exists(Path.ChangeExtension(localPath, ".png")))
        {
            aircraft.ImageUrl = Path.Combine(AircraftImagesBlobRelativePath, aircraft.Registration.ToLower() + ".png");
        }
        else
        {
            aircraft.ImageUrl = Path.Combine(StockImagesBlobRelativePath, "stock-aircraft-img" + ".png");
        }

        return View(aircraft);
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddAircraft()
    {
        AircraftFormModel aircraft = new AircraftFormModel();

        return View(aircraft);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddAircraft(AircraftFormModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        try
        {
            var form = await Request.ReadFormAsync();
            var picturePath = await ImageHelper.UploadAircraftPicture(form.Files.FirstOrDefault(), model.Registration, _hostingEnvironment.WebRootPath);

            if (string.IsNullOrEmpty(picturePath))
            {
                model.ImagePathUrl = Path.Combine(StockImagesBlobRelativePath, "stock-aircraft-img" + ".png");
            }
            else
            {
                BlobContainerClient blobAircraft = _blobServiceClient.GetBlobContainerClient(AircraftImagesContainerName);

                await UploadFromFileAsync(blobAircraft, picturePath);

                model.ImagePathUrl = Path.Combine(AircraftImagesBlobRelativePath, model.Registration.ToLower() + ".jpg");

                ImageHelper.SynchronizeAircraftImages(_hostingEnvironment.WebRootPath, model.Registration.ToLower());
            }

            await _aircraftService.AddAircraftAsync(model);
        }
        catch
        {
            return BadRequest();
        }

        if (!string.IsNullOrEmpty(model.Error))
        {
            return View(model);
        }

        StatusMessage = "Aircraft added successfully!";
        return RedirectToAction("Index", "AdminPanel", new { area = AdminRole });
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditAircraft(string aircraftId)
    {
        var aircraft = await _aircraftService.GetAircraftbyIdAsync(aircraftId);

        return View(aircraft);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditAircraft(string aircraftId, AircraftFormModel model)
    {
        var aircraft = await _aircraftService.GetAircraftbyIdAsync(aircraftId);

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        aircraft.Registration = model.Registration;
        aircraft.Equipment = model.Equipment;

        try
        {
            var form = await Request.ReadFormAsync();
            var picturePath = await ImageHelper.UploadAircraftPicture(form.Files.FirstOrDefault(), model.Registration, _hostingEnvironment.WebRootPath);

            if (!string.IsNullOrEmpty(picturePath))
            {
                BlobContainerClient blobAircraft = _blobServiceClient.GetBlobContainerClient(AircraftImagesContainerName);

                await UploadFromFileAsync(blobAircraft, picturePath);

                model.ImagePathUrl = Path.Combine(AircraftImagesBlobRelativePath, model.Registration.ToLower() + ".jpg");

                ImageHelper.SynchronizeAircraftImages(_hostingEnvironment.WebRootPath, model.Registration.ToLower());
            }
            else
            {
                model.ImagePathUrl = aircraft.ImagePathUrl;
            }

            await _aircraftService.EditAircraftAsync(aircraftId, model);
        }
        catch
        {
            return BadRequest();
        }

        StatusMessage = "Aircraft edited successfully!";
        return RedirectToAction("Index", "AdminPanel", new { area = AdminRole });
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeleteAircraft(string[] aircraftIds)
    {
        try
        {
            var picturesToDelete = await _aircraftService.GetAircraftPictureIdsAsync(aircraftIds);

            await _aircraftService.DeleteAircraftAsync(aircraftIds);

            await ImageHelper.DeleteAircraftImages(_hostingEnvironment.WebRootPath, picturesToDelete.ToArray());

            return Json(new { success = true, message = "Selected aircraft were deleted successfully!" });
        }
        catch
        {
            return Json(new { success = false, message = "Error: Something went wrong and the selected aircraft were not deleted!" });
        }
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeletedHistoryAircraft()
    {
        IEnumerable<AircraftAllViewModel> deletedAircraft;

        try
        {
            deletedAircraft = await _aircraftService.GetDeletedAircraftAsync();
        }
        catch
        {
            return BadRequest();
        }

        return PartialView("_DeletedAircraftPartial", deletedAircraft);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> RepairAircraft(string[] aircraftIds)
    {
        try
        {
            await _aircraftService.RepairAircraftAsync(aircraftIds);

            return Json(new { success = true, message = "Selected aircraft repaired successfully!" });
        }
        catch
        {
            return Json(new { success = false, message = "Error: Something went wrong and the selected aircraft were not repaired!" });
        }
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> TotaledAircraft()
    {
        IEnumerable<AircraftAllViewModel> totaledAircraft;

        try
        {
            totaledAircraft = await _aircraftService.GetTotaledAircraftAsync();
        }
        catch
        {
            return BadRequest();
        }

        return PartialView("_TotaledAircraftPartial", totaledAircraft);
    }
}

SkyTracker.Web/Controllers/HeraldController.cs
namespace SkyTracker.Web.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using SkyTracker.Services.Data.Interfaces;

using ViewModels.Herald;

using X.PagedList;

using static Common.GeneralApplicationContants;
using static Common.UserRoleNames;

/// <summary>
/// Herald Controller. Used for Herald related actions.
/// </summary>

[Authorize]
public class HeraldController : Controller
{
    private readonly IHeraldService _heraldService;

    public HeraldController(IHeraldService heraldService)
    {
        _heraldService = heraldService;
    }

    [TempData]
    public string StatusMessage { get; set; }

    [HttpGet]
    public async Task<IActionResult> All(string sortType, int? page, int? pageSize)
    {
        IEnumerable<HeraldAllViewModel>? heralds;

        int pageNumber = page ?? DefaultStartPagePagination;
        int itemsPerPage = pageSize ?? DefaultListEntitiesPerPage;

        switch (sortType)
        {
            case "date_asc":
                heralds = await _heraldService.GetAllHeraldsSortedByDateAscAsync();
                break;
            case "type_asc":
                heralds = await _heraldService.GetAllHeraldsSortedByTypeAscAsync();
                break;
            case "type_desc":
                heralds = await _heraldService.GetAllHeraldsSortedByTypeDescAsync();
                break;
            default:
                heralds = await _heraldService.GetAllHeraldsAsync();
                break;
        }

        var totalItemCount = heralds.Count();

        var totalPages = (int)Math.Ceiling((double)totalItemCount / itemsPerPage);
        if (pageNumber > totalPages || itemsPerPage != pageSize)
        {
            pageNumber = 1;
        }

        var pagedHeralds = heralds.ToPagedList(pageNumber, itemsPerPage);

        var updatedPagedList = new StaticPagedList<HeraldAllViewModel>(pagedHeralds, pagedHeralds.GetMetaData());

        var updatedPagedListWithPageNumber = new StaticPagedList<HeraldAllViewModel>(
            updatedPagedList, pageNumber, itemsPerPage, totalItemCount);

        return View(updatedPagedListWithPageNumber);
    }

    [HttpGet]
    public async Task<IActionResult> GetDetails(string occurrenceId)
    {
        var occurence = await _heraldService.GetDetailsById(occurrenceId);

        return View(occurence);
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddHerald()
    {
        var types = await _heraldService.GetHeraldTypeAsync();

        var aircraftCollection = await _heraldService.GetAircraftForHerald();

        HeraldFormModel model = new HeraldFormModel
        {
            Occurrence = DateTime.UtcNow,
            HeraldTypes = types,
            AircraftHeralds = aircraftCollection
        };

        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddHerald(HeraldFormModel model)
    {
        if (!ModelState.IsValid)
        {
            model.HeraldTypes = await _heraldService.GetHeraldTypeAsync();
            model.AircraftHeralds = await _heraldService.GetAircraftForHerald();

            return View(model);
        }

        try
        {
            var selectedType = model.HeraldTypes.FirstOrDefault(t => t.Type.ToString() == model.TypeOccurrence);
            if (selectedType != null)
                model.TypeOccurrence = selectedType.Type.ToString();

            await _heraldService.AddHeraldAsync(model);
        }
        catch
        {
            return BadRequest();
        }

        if (!string.IsNullOrEmpty(model.Error))
        {
            model.HeraldTypes = await _heraldService.GetHeraldTypeAsync();

            return View(model);
        }

        StatusMessage = "Herald added successfully!";
        return RedirectToAction("Index", "AdminPanel", new { area = AdminRole });
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditHerald(string heraldId)
    {
        var heraldTypes = await _heraldService.GetHeraldTypeAsync();

        var aircraftCollection = await _heraldService.GetAircraftForHerald();

        var herald = await _heraldService.GetHeraldbyIdAsync(heraldId);

        herald.HeraldTypes = heraldTypes;
        herald.AircraftHeralds = aircraftCollection;

        return View(herald);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditHerald(string heraldId, HeraldFormModel model)
    {
        var heraldTypes = await _heraldService.GetHeraldTypeAsync();

        var aircraftCollection = await _heraldService.GetAircraftForHerald();

        var herald = await _heraldService.GetHeraldbyIdAsync(heraldId);

        herald.HeraldTypes = heraldTypes;
        herald.AircraftHeralds = aircraftCollection;

        if (!ModelState.IsValid)
        {
            return View(herald);
        }

        herald.Occurrence = model.Occurrence;
        herald.TypeOccurrence = model.TypeOccurrence;
        herald.Details = model.Details;
        herald.AircraftId = model.AircraftId;

        try
        {
            await _heraldService.EditHeraldAsync(heraldId, herald);
        }
        catch
        {
            return BadRequest();
        }

        StatusMessage = "Herald edited successfully!";
        return RedirectToAction("Index", "AdminPanel", new { area = AdminRole });
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeleteHerald(string[] heraldIds)
    {
        try
        {
            await _heraldService.DeleteHeraldAsync(heraldIds);
            return Json(new { success = true, message = "Selected heralds were deleted successfully!" });
        }
        catch
        {
            return Json(new { success = false, message = "Error: Something went wrong and the selected heralds were not deleted!" });
        }
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeletedHistoryHeralds()
    {
        IEnumerable<HeraldAllViewModel> deletedHeralds;

        try
        {
            deletedHeralds = await _heraldService.GetDeletedHeraldsAsync();
        }
        catch
        {
            return BadRequest();
        }

        return PartialView("_DeletedHeraldsPartial", deletedHeralds);
    }
}

SkyTracker.Web/Views/Aircraft/AddAircraft.cshtml
@model AircraftFormModel

@{
    ViewBag.Title = "Add a new Aircraft";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@{
    if (!string.IsNullOrEmpty(Model.Error))
    {
        <div class="alert alert-warning" role="alert">
            @Model.Error
        </div>
    }
}

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="AddAircraft" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label asp-for="@Model.Id" class="form-label-add-edit">A/C ID</label>
                <input asp-for="@Model.Id" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Id" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Registration" class="form-label-add-edit">Registration</label>
                <input asp-for="@Model.Registration" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Registration" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Equipment" class="form-label-add-edit">A/C Type</label>
                <input asp-for="@Model.Equipment" class="form-control" aria-required="false" />
                <span asp-validation-for="@Model.Equipment" class="text-danger"></span>
            </div>

            <div class="col-md-4">
                <div class="mb-3 pt-3 pb-3">
                    <input class="form-control mb-2" type="file" name="file" id="file" />
                </div>
            </div>

            <div class="mb-3">
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Add Aircraft" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SkyTracker.Web/Views/Aircraft/All.cshtml
@model IEnumerable<AircraftAllViewModel>

@{
    ViewBag.Title = "All Aircraft";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    @foreach (var aircraft in Model)
    {
        <div class="col-md-6 col-lg-4 mb-2">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center fw-bold">@aircraft.Registration</h5>
                    <p class="card-text">Aircraft Type: @aircraft.Equipment</p>

                    <div class="d-flex justify-content-center text-center">
                        <a href="@Url.Action("GetDetailsAircraft", "Aircraft", new { aircraftId = aircraft.Id })" class="btn btn-primary btn-rounded w-50">Aircraft Details</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SkyTracker.Web/Views/Aircraft/EditAircraft.cshtml
@model AircraftFormModel

@{
    ViewBag.Title = "Edit an existing Aircraft";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="EditAircraft" asp-route-aircraftId="@Model.Id" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label asp-for="@Model.Registration" class="form-label-add-edit">Registration</label>
                <input asp-for="@Model.Registration" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Registration" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Equipment" class="form-label-add-edit">A/C Type</label>
                <input asp-for="@Model.Equipment" class="form-control" aria-required="false" />
                <span asp-validation-for="@Model.Equipment" class="text-danger"></span>
            </div>

            <div class="col-md-4">
                <div class="mb-3">
                    <input class="form-control mb-2" type="file" name="file" id="file" />
                </div>
            </div>

            <div class="mb-3">
                <input type="hidden" asp-for="@Model.Id" />
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Edit Aircraft" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SkyTracker.Web/Views/Aircraft/GetDetailsAircraft.cshtml
@model AircraftDetailsViewModel

@{
    ViewBag.Title = "Aircraft Details";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="~/@Model.ImageUrl" alt="aircraft-picture" class="img-fluid" style="max-width:600px">
        </div>
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-body">
                    <h2>@Model.Registration</h2>
                    <p>Aircraft Type: @Model.Equipment</p>
                    <p>Tracker Id: @Model.Id</p>
                    @if (Model.IsTotaled)
                    {
                        <a class="mb-2" href="@Url.Action("GetDetails", "Herald", new { area = "", occurrenceId = Model.Herald })">
                            <span class="fw-bold">Associated Herald</span>
                        </a>
                    }

                    <div class="d-flex justify-content-center text-center w-100 mt-2">
                        <a asp-controller="Aircraft" asp-action="All" class="btn btn-secondary btn-rounded">Back to All Aircraft</a>
                    </div>
                </div>
            </div>

            
        </div>        
    </div>
</div>

<style>
    .card {
        margin: 0 auto;
        max-width: 400px;
    }
</style>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SkyTracker.Web/Views/Aircraft/_DeletedAircraftPartial.cshtml
@model IEnumerable<AircraftAllViewModel>

<button id="goBackToAircraft" class="btn btn-secondary">Go Back to Aircraft</button>

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th>Aircraft Id</th>
            <th>A/C Registration</th>
            <th>A/C Type</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Registration</td>
                <td>@item.Equipment</td>
            </tr>
        }
    </tbody>
</table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        // Handle the click event of the "Go Back to Aircraft" button
        $('#goBackToAircraft').click(function () {
            // Load the normal "Aircraft" partial view
            loadPartialViewOnClick('@Url.Action("AircraftPartial", "AdminPanel", new {area = "Admin"})');
        });
    });
</script>

SkyTracker.Web/Views/Aircraft/_TotaledAircraftPartial.cshtml
@model IEnumerable<AircraftAllViewModel>

<div id="statusMessageContainer"></div>

<button id="goBackToAircraft" class="btn btn-secondary">Go Back to Aircraft</button>
<button id="repairSelected" class="btn btn-danger">Repair Selected</button>

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>Aircraft Id</th>
            <th>A/C Registration</th>
            <th>A/C Type</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="row-@item.Id">
                <td><input type="checkbox" name="selectedAircraft" value="@item.Id" /></td>
                <td>@item.Id</td>
                <td>@item.Registration</td>
                <td>@item.Equipment</td>
            </tr>
        }
    </tbody>
</table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        // Handle the click event of the "Go Back to Aircraft" button
        $('#goBackToAircraft').click(function () {
            // Load the normal "Aircraft" partial view
            loadPartialViewOnClick('@Url.Action("AircraftPartial", "AdminPanel", new {area = "Admin"})');
        });

        // Repair aircraft functionality
        $('#repairSelected').click(function () {
            var selectedUsers = $('input[name="selectedAircraft"]:checked');
            var selectedIds = [];

            selectedUsers.each(function () {
                selectedIds.push($(this).val());
            });

            if (selectedIds.length === 0) {
                alert('Please select at least one aircraft.');
                return;
            }

            if (confirm('Are you sure you want to repair the selected aircraft?')) {
                $.ajax({
                    url: '@Url.Action("RepairAircraft", "Aircraft", new {area = ""})',
                    type: 'POST',
                    data: { aircraftIds: selectedIds },
                    success: function (result) {
                        if (result.success) {
                            selectedUsers.closest('tr').remove();
                        } else {
                            alert('An error occurred while repairing the aircraft. Please try again.');
                        }

                        if (result.message) {
                            var alertDiv = $('<div>');
                            alertDiv.text(result.message);

                            if (result.message.includes("Error:")) {
                                alertDiv.addClass('alert alert-danger');
                            } else {
                                alertDiv.addClass('alert alert-success');
                            }

                            $('#statusMessageContainer').empty().append(alertDiv);

                            // Hide the status message after a certain time interval (in milliseconds)
                            var statusMessageTimeout = 5000; // 5 seconds
                            var statusMessageElement = $("#statusMessageContainer");

                            setTimeout(function () {
                                statusMessageElement.fadeOut("slow", function () {
                                    $(this).empty(); // Clear the container content
                                });
                            }, statusMessageTimeout);
                        }
                    },
                    error: function () {
                        alert('An error occurred while repairing the aircraft. Please try again.');
                    }
                });
            }
        });

    });
</script>