SkyTracker.Web/Controllers/FlightController.cs
namespace SkyTracker.Web.Controllers;

using Azure.Storage.Blobs;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using SkyTracker.Services.Data.Interfaces;

using ViewModels.Flight;

using X.PagedList;

using static Common.GeneralApplicationContants;
using static Common.UserRoleNames;
using static Configuration.DownloadBlob;

/// <summary>
/// Flight Controller. Used for Flight related actions.
/// </summary>

[Authorize]
public class FlightController : Controller
{
    private readonly IFlightService _flightService;
    private readonly BlobServiceClient _blobServiceClient;
    private readonly IWebHostEnvironment _hostingEnvironment;

    public FlightController(IFlightService flightService, BlobServiceClient blobServiceClient, IWebHostEnvironment hostingEnvironment)
    {
        _flightService = flightService;
        _blobServiceClient = blobServiceClient;
        _hostingEnvironment = hostingEnvironment;
    }

    [TempData]
    public string StatusMessage { get; set; }

    [HttpGet]
    public async Task<IActionResult> All(string sortType, int? page, int? pageSize)
    {
        IEnumerable<FlightAllViewModel> flights;

        int pageNumber = page ?? DefaultStartPagePagination;
        int itemsPerPage = pageSize ?? DefaultListEntitiesPerPage;

        switch (sortType)
        {
            case "id_desc":
                flights = await _flightService.GetAllFlightsSortedByFlightIdDescAsync();
                break;
            case "arp_asc":
                flights = await _flightService.GetAllFlightsSortedByArpAscAsync();
                break;
            case "arp_desc":
                flights = await _flightService.GetAllFlightsSortedByArpDescAsync();
                break;
            default:
                flights = await _flightService.GetAllFlightsAsync();
                break;
        }

        var totalItemCount = flights.Count();

        var totalPages = (int)Math.Ceiling((double)totalItemCount / itemsPerPage);
        if (pageNumber > totalPages || itemsPerPage != pageSize)
        {
            pageNumber = 1;
        }

        var pagedFlights = flights.ToPagedList(pageNumber, itemsPerPage);

        var updatedPagedList = new StaticPagedList<FlightAllViewModel>(pagedFlights, pagedFlights.GetMetaData());

        var updatedPagedListWithPageNumber = new StaticPagedList<FlightAllViewModel>(
            updatedPagedList, pageNumber, itemsPerPage, updatedPagedList.TotalItemCount);

        return View(updatedPagedListWithPageNumber);
    }

    [HttpGet]
    public async Task<IActionResult> GetDetailsFlight(string flightId)
    {
        var flight = await _flightService.GetFlightDetailsByIdAsync(flightId);

        BlobContainerClient blobAircraft = _blobServiceClient.GetBlobContainerClient(AircraftImagesContainerName);

        BlobClient blob = blobAircraft.GetBlobClient(flight.Aircraft.Registration?.ToLower() + ".jpg");

        string localPath = Path.Combine(_hostingEnvironment.WebRootPath, AircraftImagesBlobRelativePath, flight.Aircraft.Registration?.ToLower() + ".jpg");

        if (await blob.ExistsAsync())
        {
            await DownloadBlobToFileAsync(blob, localPath);

            flight.Aircraft.ImagePathUrl = Path.Combine(AircraftImagesBlobRelativePath, flight.Aircraft.Registration?.ToLower() + ".jpg");
        }
        else
        {
            blobAircraft = _blobServiceClient.GetBlobContainerClient(StockImagesContainerName);
            blob = blobAircraft.GetBlobClient("stock-aircraft-img" + ".png");
            localPath = Path.Combine(_hostingEnvironment.WebRootPath, StockImagesBlobRelativePath, "stock-aircraft-img" + ".png");

            await DownloadBlobToFileAsync(blob, localPath);

            flight.Aircraft.ImagePathUrl = Path.Combine(StockImagesBlobRelativePath, "stock-aircraft-img" + ".png");
        }

        return View(flight);
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddFlight()
    {
        var airports = await _flightService.GetAirportsCollectionAsync();
        var aircraft = await _flightService.GetAircraftsCollectionAsync();

        FlightFormModel model = new FlightFormModel()
        {
            AircraftList = aircraft,
            AirportListDeparture = airports,
            AirportListArrival = airports,
            AirportListActual = airports,
            AirporListReserved = airports
        };

        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddFlight(FlightFormModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        try
        {
            await _flightService.AddFlightAsync(model);
        }
        catch
        {
            return BadRequest();
        }

        if (!string.IsNullOrEmpty(model.Error))
        {
            model.AircraftList = await _flightService.GetAircraftsCollectionAsync();
            model.AirportListDeparture = await _flightService.GetAirportsCollectionAsync();
            model.AirportListArrival = await _flightService.GetAirportsCollectionAsync();
            model.AirportListActual = await _flightService.GetAirportsCollectionAsync();
            model.AirporListReserved = await _flightService.GetAirportsCollectionAsync();

            return View(model);
        }

        StatusMessage = "Flight added successfully!";
        return RedirectToAction("Index", "AdminPanel", new {area = AdminRole});
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditFlight(string flightId)
    {
        var airports = await _flightService.GetAirportsCollectionAsync();
        var aircraft = await _flightService.GetAircraftsCollectionAsync();

        var flight = await _flightService.GetFlightbyIdAsync(flightId);

        flight.AircraftList = aircraft;
        flight.AirportListDeparture = airports;
        flight.AirportListArrival = airports;
        flight.AirportListActual = airports;
        flight.AirporListReserved = airports;

        return View(flight);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditFlight(string flightId, FlightFormModel model)
    {
        var airports = await _flightService.GetAirportsCollectionAsync();
        var aircraft = await _flightService.GetAircraftsCollectionAsync();

        var flight = await _flightService.GetFlightbyIdAsync(flightId);

        flight.AircraftList = aircraft;
        flight.AirportListDeparture = airports;
        flight.AirportListArrival = airports;
        flight.AirportListActual = airports;
        flight.AirporListReserved = airports;

        model.AirportListDeparture = airports;
        model.AirportListArrival = airports;
        model.AirportListActual = airports;
        model.AirporListReserved = airports;

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        flight.Registration = model.Registration;
        flight.Equipment = model.Equipment;
        flight.Callsign = model.Callsign;
        flight.FlightNumber = model.FlightNumber;
        flight.DepartureId = model.DepartureId;
        flight.ScheduledArrival = model.ScheduledArrival;
        flight.RealArrival = model.RealArrival;
        flight.Reserved = model.Reserved;

        try
        {
            await _flightService.EditFlightAsync(flightId, model);
        }
        catch
        {
            return BadRequest();
        }

        StatusMessage = "Flight edited successfully!";
        return RedirectToAction("Index", "AdminPanel", new {area = AdminRole});
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeleteFlight(string[] flightIds)
    {
        try
        {
            await _flightService.DeleteFlightAsync(flightIds);
            return Json(new { success = true, message = "Selected flights were deleted successfully!" });
        }
        catch
        {
            return Json(new { success = false, message = "Error: Something went wrong and the selected flights were not deleted" });
        }
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeletedHistoryFlights()
    {
        IEnumerable<FlightAllViewModel> deletedFlights;

        try
        {
            deletedFlights = await _flightService.GetDeletedFlightsAsync();
        }
        catch
        {
            return BadRequest();
        }

        return PartialView("_DeletedFlightsPartial", deletedFlights);
    }
}

SkyTracker.Web/Controllers/HeraldController.cs
namespace SkyTracker.Web.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using SkyTracker.Services.Data.Interfaces;

using ViewModels.Herald;

using X.PagedList;

using static Common.GeneralApplicationContants;
using static Common.UserRoleNames;

/// <summary>
/// Herald Controller. Used for Herald related actions.
/// </summary>

[Authorize]
public class HeraldController : Controller
{
    private readonly IHeraldService _heraldService;

    public HeraldController(IHeraldService heraldService)
    {
        _heraldService = heraldService;
    }

    [TempData]
    public string StatusMessage { get; set; }

    [HttpGet]
    public async Task<IActionResult> All(string sortType, int? page, int? pageSize)
    {
        IEnumerable<HeraldAllViewModel>? heralds;

        int pageNumber = page ?? DefaultStartPagePagination;
        int itemsPerPage = pageSize ?? DefaultListEntitiesPerPage;

        switch (sortType)
        {
            case "date_asc":
                heralds = await _heraldService.GetAllHeraldsSortedByDateAscAsync();
                break;
            case "type_asc":
                heralds = await _heraldService.GetAllHeraldsSortedByTypeAscAsync();
                break;
            case "type_desc":
                heralds = await _heraldService.GetAllHeraldsSortedByTypeDescAsync();
                break;
            default:
                heralds = await _heraldService.GetAllHeraldsAsync();
                break;
        }

        var totalItemCount = heralds.Count();

        var totalPages = (int)Math.Ceiling((double)totalItemCount / itemsPerPage);
        if (pageNumber > totalPages || itemsPerPage != pageSize)
        {
            pageNumber = 1;
        }

        var pagedHeralds = heralds.ToPagedList(pageNumber, itemsPerPage);

        var updatedPagedList = new StaticPagedList<HeraldAllViewModel>(pagedHeralds, pagedHeralds.GetMetaData());

        var updatedPagedListWithPageNumber = new StaticPagedList<HeraldAllViewModel>(
            updatedPagedList, pageNumber, itemsPerPage, totalItemCount);

        return View(updatedPagedListWithPageNumber);
    }

    [HttpGet]
    public async Task<IActionResult> GetDetails(string occurrenceId)
    {
        var occurence = await _heraldService.GetDetailsById(occurrenceId);

        return View(occurence);
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddHerald()
    {
        var types = await _heraldService.GetHeraldTypeAsync();

        var aircraftCollection = await _heraldService.GetAircraftForHerald();

        HeraldFormModel model = new HeraldFormModel
        {
            Occurrence = DateTime.UtcNow,
            HeraldTypes = types,
            AircraftHeralds = aircraftCollection
        };

        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddHerald(HeraldFormModel model)
    {
        if (!ModelState.IsValid)
        {
            model.HeraldTypes = await _heraldService.GetHeraldTypeAsync();
            model.AircraftHeralds = await _heraldService.GetAircraftForHerald();

            return View(model);
        }

        try
        {
            var selectedType = model.HeraldTypes.FirstOrDefault(t => t.Type.ToString() == model.TypeOccurrence);
            if (selectedType != null)
                model.TypeOccurrence = selectedType.Type.ToString();

            await _heraldService.AddHeraldAsync(model);
        }
        catch
        {
            return BadRequest();
        }

        if (!string.IsNullOrEmpty(model.Error))
        {
            model.HeraldTypes = await _heraldService.GetHeraldTypeAsync();

            return View(model);
        }

        StatusMessage = "Herald added successfully!";
        return RedirectToAction("Index", "AdminPanel", new { area = AdminRole });
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditHerald(string heraldId)
    {
        var heraldTypes = await _heraldService.GetHeraldTypeAsync();

        var aircraftCollection = await _heraldService.GetAircraftForHerald();

        var herald = await _heraldService.GetHeraldbyIdAsync(heraldId);

        herald.HeraldTypes = heraldTypes;
        herald.AircraftHeralds = aircraftCollection;

        return View(herald);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditHerald(string heraldId, HeraldFormModel model)
    {
        var heraldTypes = await _heraldService.GetHeraldTypeAsync();

        var aircraftCollection = await _heraldService.GetAircraftForHerald();

        var herald = await _heraldService.GetHeraldbyIdAsync(heraldId);

        herald.HeraldTypes = heraldTypes;
        herald.AircraftHeralds = aircraftCollection;

        if (!ModelState.IsValid)
        {
            return View(herald);
        }

        herald.Occurrence = model.Occurrence;
        herald.TypeOccurrence = model.TypeOccurrence;
        herald.Details = model.Details;
        herald.AircraftId = model.AircraftId;

        try
        {
            await _heraldService.EditHeraldAsync(heraldId, herald);
        }
        catch
        {
            return BadRequest();
        }

        StatusMessage = "Herald edited successfully!";
        return RedirectToAction("Index", "AdminPanel", new { area = AdminRole });
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeleteHerald(string[] heraldIds)
    {
        try
        {
            await _heraldService.DeleteHeraldAsync(heraldIds);
            return Json(new { success = true, message = "Selected heralds were deleted successfully!" });
        }
        catch
        {
            return Json(new { success = false, message = "Error: Something went wrong and the selected heralds were not deleted!" });
        }
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeletedHistoryHeralds()
    {
        IEnumerable<HeraldAllViewModel> deletedHeralds;

        try
        {
            deletedHeralds = await _heraldService.GetDeletedHeraldsAsync();
        }
        catch
        {
            return BadRequest();
        }

        return PartialView("_DeletedHeraldsPartial", deletedHeralds);
    }
}

SkyTracker.Web/Controllers/RadarController.cs
namespace SkyTracker.Web.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using SkyTracker.Services.Data.Interfaces;

/// <summary>
/// Radar Controller. Used to display the map with the flight and airport data.
/// </summary>

[Authorize]
public class RadarController : Controller
{
    private readonly IRadarService _radarService;

    public RadarController(IRadarService radarService)
    {
        _radarService = radarService;
    }

    public async Task<IActionResult> Map()
    {
        var airportAndFlightDataLocations = await _radarService.GetFlightAndAirportDataAsync();

        return View(airportAndFlightDataLocations);
    }
}

SkyTracker.Web/Controllers/SearchController.cs
namespace SkyTracker.Web.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using SkyTracker.Services.Data.Interfaces;

/// <summary>
/// Search Controller. Used to search for aircraft, airports, and flights.
/// </summary>

[Authorize]
public class SearchController : Controller
{
    private readonly ISearchService _searchService;

    public SearchController(ISearchService searchService)
    {
        _searchService = searchService;
    }

    public async Task<IActionResult> IndexSearch(string query, string[] properties, string modelType)
    {
        string[] mappedProperties = properties.SelectMany(p => p.Split(',')).ToArray();

        switch (modelType)
        {
            case "aircraft":
                var aircraftResults = await _searchService.SearchAircraftAsync(query, mappedProperties);
                ViewBag.AircraftResults = aircraftResults;
                ViewBag.ModelType = modelType;
                break;
            case "airports":
                var airportResults = await _searchService.SearchAirportsAsync(query, mappedProperties);
                ViewBag.AirportResults = airportResults;
                ViewBag.ModelType = modelType;
                break;
            case "flights":
                var flightResults = await _searchService.SearchFlightsAsync(query, mappedProperties);
                ViewBag.FlightResults = flightResults;
                ViewBag.ModelType = modelType;
                break;
        }

        return View();
    }
}

SkyTracker.Web/Views/Shared/_Layout.cshtml
@using static SkyTracker.Common.GeneralApplicationContants

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sky Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" /> @*Added font awesome for icons*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg" style="background: linear-gradient(180.3deg, rgb(221, 221, 221) 5.5%, rgb(110, 136, 161) 90.2%);">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/static-images/logo.png" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
                    Sky Tracker
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link text-dark" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Radar" asp-action="Map">Radar</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Database
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Aircraft" asp-action="All">Aircraft</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Airport" asp-action="All">Airports</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Flight" asp-action="All">Historic Flights</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="IndexSearch">Search Database</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Herald" asp-action="All">Herald News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>
                    </ul>

                </div>
                @*Show quick access button for Administrative Panel to Admin and Moderator*@
                @if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                {
                    <a href="@Url.Action("Index", "AdminPanel", new {area = "Admin"})">
                        <button type="button" class="btn btn-outline-danger btn-floating" data-mdb-ripple-color="dark" style="margin-right: 10px;">
                            <i class="fas fa-plane-departure"></i>
                        </button>
                    </a>
                }

                <partial name="_LoginPartial" />
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*Off-canvas functionality*@
    <div class="offcanvas offcanvas-end" tabindex="-1" id="settingsOffCanvas" aria-labelledby="settingsOffCanvasLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="settingsOffCanvasLabel">Account Settings</h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <p><a class="nav-link text-dark" asp-area="" asp-controller="AccountManagement" asp-action="ProfileDisplay">User Profile</a></p>
            <p><a class="nav-link text-dark" asp-area="" asp-controller="AccountManagement" asp-action="EmailChange">Change Email</a></p>
            <p><a class="nav-link text-dark" asp-area="" asp-controller="AccountManagement" asp-action="PasswordChange">Change Password</a></p>
            <p><a class="nav-link text-dark" asp-area="" asp-controller="AccountManagement" asp-action="PhoneNumberChange">Change Phone</a></p>
            <p><a class="nav-link text-dark" asp-area="" asp-controller="AccountManagement" asp-action="DownloadPersonalData">Download Personal Data</a></p>
            <p><a class="nav-link text-dark" asp-area="" asp-controller="AccountManagement" asp-action="DeletePersonalData">Delete Personal Data</a></p>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @YearCreated - Sky Tracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        // Get the profile trigger container element
        const profileTriggerContainer = document.getElementById('profileTriggerContainer');

        // Get the off-canvas element
        const offCanvasElement = new bootstrap.Offcanvas(document.getElementById('settingsOffCanvas'));

        // Add an event listener to the profile trigger container
        profileTriggerContainer.addEventListener('click', () => {
            offCanvasElement.show();
        });
    </script>
</body>
</html>