SkyTracker.Web/Controllers/AirportController.cs
namespace SkyTracker.Web.Controllers;

using System.IO;

using Azure.Storage.Blobs;

using Configuration;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using SkyTracker.Services.Data.Interfaces;

using ViewModels.Airport;

using static Common.GeneralApplicationContants;
using static Common.UserRoleNames;
using static Configuration.UploadBlob;

/// <summary>
/// Airport Controller. Used for managing airports.
/// </summary>

[Authorize]
public class AirportController : Controller
{
    private readonly IAirportsService _airportsService;
    private readonly BlobServiceClient _blobServiceClient;
    private readonly IWebHostEnvironment _hostingEnvironment;

    public AirportController(IAirportsService airportsService, BlobServiceClient blobServiceClient, IWebHostEnvironment hostingEnvironment)
    {
        _airportsService = airportsService;
        _blobServiceClient = blobServiceClient;
        _hostingEnvironment = hostingEnvironment;
    }

    [TempData]
    public string StatusMessage { get; set; }

    [HttpGet]
    public async Task<IActionResult> All()
    {
        var airports = await _airportsService.GetAllAirportsAsync();

        return View(airports);
    }

    [HttpGet]
    public async Task<IActionResult> GetDetailsAirport(string iata)
    {
        var airport = await _airportsService.GetAirportDetailsByIata(iata);

        string localPath = Path.Combine(_hostingEnvironment.WebRootPath, AirportImagesBlobRelativePath, airport.IATA.ToLower());

        if (System.IO.File.Exists(Path.ChangeExtension(localPath, ".jpg")))
        {
            airport.ImageUrl = Path.Combine(AirportImagesBlobRelativePath, airport.IATA.ToLower() + ".jpg");
        }
        else if (System.IO.File.Exists(Path.ChangeExtension(localPath, ".png")))
        {
            airport.ImageUrl = Path.Combine(AirportImagesBlobRelativePath, airport.IATA.ToLower() + ".png");
        }
        else
        {
            airport.ImageUrl = Path.Combine(StockImagesBlobRelativePath, "stock-airport-img" + ".png");
        }

        return View(airport);
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddAirport()
    {
        var runways = await _airportsService.GetRunwaysCollectionAsync();

        AirportFormModel model = new AirportFormModel
        {
            Runways = runways
        };

        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> AddAirport(AirportFormModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        try
        {
            var form = await Request.ReadFormAsync();
            var picturePath = await ImageHelper.UploadAirportPicture(form.Files.FirstOrDefault(), model.IATA, _hostingEnvironment.WebRootPath);

            if (string.IsNullOrEmpty(picturePath))
            {
                model.ImagePathUrl = Path.Combine(StockImagesBlobRelativePath, "stock-airport-img" + ".png");
            }
            else
            {
                BlobContainerClient blobAirport = _blobServiceClient.GetBlobContainerClient(AirportImagesContainerName);

                await UploadFromFileAsync(blobAirport, picturePath);

                model.ImagePathUrl = Path.Combine(AirportImagesBlobRelativePath, model.IATA.ToLower() + ".jpg");

                ImageHelper.SynchronizeAirportImages(_hostingEnvironment.WebRootPath, model.IATA.ToLower());
            }

            await _airportsService.AddAirportAsync(model);
            await _airportsService.AddRunwayToAirportAsync(model.IATA, model.RunwayId);
        }
        catch
        {
            return BadRequest();
        }

        if (!string.IsNullOrEmpty(model.Error))
        {
            model.Runways = await _airportsService.GetRunwaysCollectionAsync();
            return View(model);
        }

        StatusMessage = "Airport added successfully!";
        return RedirectToAction("Index", "AdminPanel", new { area = AdminRole });
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditAirport(string iata)
    {
        var airport = await _airportsService.GetAirportbyIataAsync(iata);

        var runways = await _airportsService.GetRunwaysCollectionAsync();

        airport.Runways = runways;

        return View(airport);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> EditAirport(string iata, AirportFormModel model)
    {
        var runways = await _airportsService.GetRunwaysCollectionAsync();

        var airport = await _airportsService.GetAirportbyIataAsync(iata);

        model.Runways = runways;

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        airport.IATA = model.IATA;
        airport.ICAO = model.ICAO;
        airport.CommonName = model.CommonName;
        airport.LocationCity = model.LocationCity;
        airport.LocationCountry = model.LocationCountry;
        airport.Lat = model.Lat;
        airport.Long = model.Long;
        airport.Elevation = model.Elevation;

        try
        {
            var form = await Request.ReadFormAsync();
            var picturePath = await ImageHelper.UploadAirportPicture(form.Files.FirstOrDefault(), model.IATA, _hostingEnvironment.WebRootPath);

            if (!string.IsNullOrEmpty(picturePath))
            {
                BlobContainerClient blobAirport = _blobServiceClient.GetBlobContainerClient(AirportImagesContainerName);

                await UploadFromFileAsync(blobAirport, picturePath);

                model.ImagePathUrl = Path.Combine(AirportImagesBlobRelativePath, airport.IATA.ToLower() + ".jpg");

                ImageHelper.SynchronizeAirportImages(_hostingEnvironment.WebRootPath, model.IATA.ToLower());
            }
            else
            {
                model.ImagePathUrl = airport.ImagePathUrl;
            }

            await _airportsService.EditAirportAsync(iata, model);
        }
        catch
        {
            return BadRequest();
        }

        StatusMessage = "Airport edited successfully!";
        return RedirectToAction("Index", "AdminPanel", new { area = AdminRole });
    }

    [HttpPost]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeleteAirport(string[] iataCodes)
    {
        try
        {
            await _airportsService.DeleteAirportAsync(iataCodes);
            await ImageHelper.DeleteAirportImages(_hostingEnvironment.WebRootPath, iataCodes);

            return Json(new { success = true, message= "Selected airports were deleted successfully!" });
        }
        catch
        {
            return Json(new { success = true, message = "Error: Something went wrong and the selected airports were not deleted!" });
        }
    }

    [HttpGet]
    [Authorize(Roles = "Admin, Moderator")]
    public async Task<IActionResult> DeletedHistoryAirports()
    {
        IEnumerable<AirportsAllViewModel> deletedAirports;
        try
        {
            deletedAirports = await _airportsService.GetDeletedAirportsAsync();
        }
        catch
        {
            return BadRequest();
        }

        return PartialView("_DeletedAirportsPartial", deletedAirports);
    }
}

SkyTracker.Web/Views/Airport/AddAirport.cshtml
@model AirportFormModel

@{
    ViewBag.Title = "Create a new Airport";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@{
    if (!string.IsNullOrEmpty(Model.Error))
    {
        <div class="alert alert-warning" role="alert">
            @Model.Error
        </div>
    }
}

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="AddAirport" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label asp-for="@Model.IATA" class="form-label-add-edit">IATA Code</label>
                <input asp-for="@Model.IATA" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.IATA" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ICAO" class="form-label-add-edit">ICAO Code</label>
                <input asp-for="@Model.ICAO" class="form-control" aria-required="false" />
                <span asp-validation-for="@Model.ICAO" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.CommonName" class="form-label-add-edit">Airport Name</label>
                <input asp-for="@Model.CommonName" class="form-control" aria-required="false" />
                <span asp-validation-for="@Model.CommonName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Elevation" class="form-label-add-edit">Elevation</label>
                <input asp-for="@Model.Elevation" class="form-control" aria-required="false" />
                <span asp-validation-for="@Model.Elevation" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.LocationCity" class="form-label-add-edit">City</label>
                <input asp-for="@Model.LocationCity" class="form-control" aria-required="false" />
                <span asp-validation-for="@Model.LocationCity" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.LocationCountry" class="form-label-add-edit">Country</label>
                <input asp-for="@Model.LocationCountry" class="form-control" aria-required="false" />
                <span asp-validation-for="@Model.LocationCountry" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Lat" class="form-label-add-edit">Geo Latitude</label>
                <input asp-for="@Model.Lat" class="form-control" aria-required="false">
                <span asp-validation-for="@Model.Lat" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Long" class="form-label-add-edit">Geo Longitude</label>
                <input asp-for="@Model.Long" class="form-control" aria-required="false">
                <span asp-validation-for="@Model.Long" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.RunwayId" class="form-label-add-edit">Airport Runway</label>
                <select asp-for="@Model.RunwayId" class="form-control" aria-required="false">
                    <option value="">Select available runway</option>
                    @foreach (var runway in Model.Runways)
                    {
                        <option value="@runway.RunwayDesignatorOne">@runway.RunwayDesignatorOne</option>
                    }
                </select>
                <span asp-validation-for="@Model.RunwayId" class="text-danger"></span>
            </div>

            <div class="col-md-4">
                <div class="mb-3">
                    <input class="form-control mb-2" type="file" name="file" id="file" />
                </div>
            </div>

            <div class="mb-3">
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Add Airport" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

SkyTracker.Web/Views/Airport/All.cshtml
@model IEnumerable<AirportsAllViewModel>

@{
    ViewBag.Title = "All Airports";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    @foreach (var airport in Model)
    {
        <div class="col-md-4 mb-2">
            <div class="card">
                <div class="card-body">
                    <p rows="2" class="card-title text-center fw-bold" style="font-size:1.1rem">@airport.CommonName</p>
                    <p class="card-text">IATA Code: @airport.IATA, ICAO Code: @airport.ICAO</p>

                    <div class="d-flex justify-content-center text-center">
                        <a href="@Url.Action("GetDetailsAirport", "Airport", new { iata = airport.IATA })" class="btn btn-primary btn-rounded w-50">Airport Details</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SkyTracker.Web/Views/Airport/EditAirport.cshtml
@model AirportFormModel

@{
    ViewBag.Title = "Edit an Airport";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="EditAirport" asp-route-aircraftId="@Model.IATA" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label asp-for="@Model.ICAO" class="form-label-add-edit">ICAO Code</label>
                <input asp-for="@Model.ICAO" class="form-control" aria-required="false" value="@Model.ICAO"/>
                <span asp-validation-for="@Model.ICAO" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.CommonName" class="form-label-add-edit">Airport Name</label>
                <input asp-for="@Model.CommonName" class="form-control" aria-required="false" value="@Model.CommonName" />
                <span asp-validation-for="@Model.CommonName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Elevation" class="form-label-add-edit">Elevation</label>
                <input asp-for="@Model.Elevation" class="form-control" aria-required="false" value="@Model.Elevation" />
                <span asp-validation-for="@Model.Elevation" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.LocationCity" class="form-label-add-edit">City</label>
                <input asp-for="@Model.LocationCity" class="form-control" aria-required="false" value="@Model.LocationCity" />
                <span asp-validation-for="@Model.LocationCity" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.LocationCountry" class="form-label-add-edit">Country</label>
                <input asp-for="@Model.LocationCountry" class="form-control" aria-required="false" value="@Model.LocationCountry" />
                <span asp-validation-for="@Model.LocationCountry" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Lat" class="form-label-add-edit">Geo Latitude</label>
                <input asp-for="@Model.Lat" class="form-control" aria-required="false" value="@Model.Lat">
                <span asp-validation-for="@Model.Lat" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Long" class="form-label-add-edit">Geo Longitude</label>
                <input asp-for="@Model.Long" class="form-control" aria-required="false" value="@Model.Long">
                <span asp-validation-for="@Model.Long" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.RunwayId" class="form-label-add-edit">Airport Runway</label>
                <select asp-for="@Model.RunwayId" class="form-control" aria-required="false">
                    <option value="@Model.RunwayId">Select available runway</option>
                    @foreach (var runway in Model.Runways)
                    {
                        <option value="@runway.RunwayDesignatorOne">@runway.RunwayDesignatorOne</option>
                    }
                </select>
                <span asp-validation-for="@Model.RunwayId" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <input class="form-control mb-2" type="file" name="file" id="file" />
                </div>
            </div>

            <div class="mb-3">
                <input type="hidden" asp-for="@Model.IATA" />
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Edit Airport" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SkyTracker.Web/Views/Airport/GetDetailsAirport.cshtml
@model AirportsDetailsViewModel

@{
    ViewBag.Title = "Airport Details";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-md-6 d-flex justify-content-start" style="border:2px solid darkgrey; padding-right: 0px; padding-left: 0px;">
        <div class="card">
            <img class="block" id="@Model.IATA" src="~/@Model.ImageUrl" alt="airport-picture" style="height:auto;" />
        </div>
    </div>

    <div class="col-md-6 d-flex" style="border:2px solid darkgrey; padding-right: 0px; padding-left: 0px;">
        <div class="card w-100">
            <div class="card-body">
                <h3 class="card-title text-center"><span class="fw-bold">@Model.CommonName</span></h3>
                <p class="mb-0"><span class="fw-bold">Elevation: </span>@Model.Elevation</p>
                <p class="mb-0"><span class="fw-bold">Location: </span>@Model.LocationCity, @Model.LocationCountry</p>
                <p class="mb-0"><span class="fw-bold">Coordinates: </span>@Model.Lat, @Model.Long</p>
                <p class="mb-0"><span class="fw-bold">IATA: </span>@Model.IATA</p>
                <p class="mb-0"><span class="fw-bold">ICAO: </span>@Model.ICAO</p>
            </div>

            <div class="card-body">
                <h3 class="card-title text-center"><span class="fw-bold">Runway Characteristics</span></h3>
                <p class="mb-0"><span class="fw-bold">Runways: </span>@Model.Runway.RunwayDesignatorOne &#47; @Model.Runway.RunwayDesignatorTwo</p>
                <p class="mb-0"><span class="fw-bold">Dimensions: </span> Length @Model.Runway.Length [m], Width @Model.Runway.Width <span class="font-italic">[m]</span></p>
                <p class="mb-0"><span class="fw-bold">Surface: </span>@Model.Runway.SurfaceType</p>
            </div>

            <div class="d-flex justify-content-center text-center">
                <a asp-controller="Airport" asp-action="All" class="btn btn-secondary btn-rounded w-50">Back to All Airports</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SkyTracker.Web/Views/Airport/_DeletedAirportsPartial.cshtml
@model IEnumerable<AirportsAllViewModel>

<button id="goBackToAirports" class="btn btn-secondary">Go Back to Airports</button>

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>IATA</th>
            <th>ICAO</th>
            <th>Country</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr id="row-@item.IATA">
                <td>@item.CommonName</td>
                <td>@item.IATA</td>
                <td>@item.ICAO</td>
                <td>@item.LocationCountry</td>
            </tr>
        }
    </tbody>
</table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        // Handle the click event of the "Go Back to Airports" button
        $('#goBackToAirports').click(function () {
            // Load the normal "Airports" partial view
            loadPartialViewOnClick('@Url.Action("AirportsPartial", "AdminPanel", new {area = "Admin"})');
        });
    });
</script>